// <auto-generated />
using System;
using Brobot.Api.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Brobot.Api.Migrations
{
    [DbContext(typeof(BrobotDbContext))]
    [Migration("20200728153609_SeedDiscordEvents")]
    partial class SeedDiscordEvents
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Brobot.Api.Entities.Channel", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<decimal>("ServerId")
                        .HasColumnName("server_id")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ChannelId");

                    b.HasIndex("ServerId");

                    b.ToTable("channel","brobot");
                });

            modelBuilder.Entity("Brobot.Api.Entities.DiscordEvent", b =>
                {
                    b.Property<int>("DiscordEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.HasKey("DiscordEventId");

                    b.ToTable("discord_event","brobot");
                });

            modelBuilder.Entity("Brobot.Api.Entities.DiscordUser", b =>
                {
                    b.Property<decimal>("DiscordUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnName("birthdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Timezone")
                        .HasColumnName("timezone")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("DiscordUserId");

                    b.ToTable("discord_user","brobot");
                });

            modelBuilder.Entity("Brobot.Api.Entities.DiscordUserChannel", b =>
                {
                    b.Property<decimal>("DiscordUserId")
                        .HasColumnName("discord_user_id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnName("channel_id")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("DiscordUserId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.ToTable("discord_user_channel","brobot");
                });

            modelBuilder.Entity("Brobot.Api.Entities.EventResponse", b =>
                {
                    b.Property<int>("EventResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal?>("ChannelId")
                        .HasColumnName("channel_id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("DiscordEventId")
                        .HasColumnName("discord_event_id")
                        .HasColumnType("integer");

                    b.Property<string>("MessageText")
                        .HasColumnName("message_text")
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnName("response_text")
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.HasKey("EventResponseId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("DiscordEventId");

                    b.ToTable("event_response","brobot");
                });

            modelBuilder.Entity("Brobot.Api.Entities.Server", b =>
                {
                    b.Property<decimal>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("ServerId");

                    b.ToTable("server","brobot");
                });

            modelBuilder.Entity("Brobot.Api.Entities.Channel", b =>
                {
                    b.HasOne("Brobot.Api.Entities.Server", "Server")
                        .WithMany("Channels")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Brobot.Api.Entities.DiscordUserChannel", b =>
                {
                    b.HasOne("Brobot.Api.Entities.Channel", "Channel")
                        .WithMany("DiscordUserChannels")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brobot.Api.Entities.DiscordUser", "DiscordUser")
                        .WithMany("DiscordUserChannels")
                        .HasForeignKey("DiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Brobot.Api.Entities.EventResponse", b =>
                {
                    b.HasOne("Brobot.Api.Entities.Channel", "Channel")
                        .WithMany("EventResponses")
                        .HasForeignKey("ChannelId");

                    b.HasOne("Brobot.Api.Entities.DiscordEvent", "DiscordEvent")
                        .WithMany("EventResponses")
                        .HasForeignKey("DiscordEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
